name: "Change Request"
description: "Formulário para solicitar uma modificação"
title: "Change Request: [Título do Pedido]"
labels: ["change request"]
assignees: ""

body:
  - type: markdown
    attributes:
      value: "## Change Request Form"

  - type: input
    id: project
    attributes:
      label: "Project"
      description: "Informe o nome do projeto"
      placeholder: "Ex: SICSA/AppProcessing"
      value: ""
    validations:
      required: true

  - type: input
    id: number
    attributes:
      label: "Request Number"
      description: "Informe o número da solicitação"
      placeholder: "Ex: 23/02"
      value: ""
    validations:
      required: true

  - type: input
    id: requester
    attributes:
      label: "Change Requester"
      description: "Informe o nome da pessoa que está solicitando a mudança"
      placeholder: "Ex: I. Sommerville"
      value: ""
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "Request Date"
      description: "Informe a data de solicitação"
      placeholder: "Ex: 20/07/12"
      value: ""
    validations:
      required: true

  - type: textarea
    id: requested_change
    attributes:
      label: "Requested Change"
      description: "Descreva a mudança solicitada"
      value: "The status of applicants (rejected, accepted, etc.) should be shown visually in the displayed list of applicants."
    validations:
      required: true

  - type: input
    id: change_analyzer
    attributes:
      label: "Change Analyzer"
      description: "Quem vai analisar a solicitação de mudança"
      placeholder: "Ex: R. Looek"
      value: ""
    validations:
      required: true

  - type: input
    id: analysis_date
    attributes:
      label: "Analysis Date"
      description: "Data da análise"
      placeholder: "Ex: 25/07/12"
      value: ""
    validations:
      required: true

  - type: textarea
    id: components_affected
    attributes:
      label: "Components Affected"
      description: "Componentes afetados pela mudança"
      value: "ApplicantListDisplay, StatusUpdater"
    validations:
      required: true

  - type: textarea
    id: associated_components
    attributes:
      label: "Associated Components"
      description: "Componentes associados"
      value: "StudentDatabase"
    validations:
      required: false

  - type: textarea
    id: change_assessment
    attributes:
      label: "Change Assessment"
      description: "Avaliação da mudança"
      value: "Relatively simple to implement by changing the display color according to status."
    validations:
      required: true

  - type: input
    id: change_priority
    attributes:
      label: "Change Priority"
      description: "Prioridade da mudança"
      placeholder: "Ex: Medium"
      value: ""
    validations:
      required: true

  - type: input
    id: estimated_effort
    attributes:
      label: "Estimated Effort"
      description: "Esforço estimado para a mudança (em horas)"
      placeholder: "Ex: 2 hours"
      value: ""
    validations:
      required: true

  - type: input
    id: decision_date
    attributes:
      label: "CCB Decision Date"
      description: "Data da decisão do Change Control Board"
      placeholder: "Ex: 30/07/12"
      value: ""
    validations:
      required: true

  - type: input
    id: release_version
    attributes:
      label: "Release Version"
      description: "Versão do Release onde a mudança será implementada"
      placeholder: "Ex: 1.2"
      value: ""
    validations:
      required: true
